name: churn-env
channels:
  - defaults
dependencies:
  - python=3.10
  - pandas>=2.0
  - numpy>=1.25
  - scikit-learn>=1.2
  - xgboost>=2.0
  - lightgbm>=3.3
  - matplotlib>=3.7
  - seaborn>=0.11
  - notebook
  - jupyterlab
  - joblib