name: churn-env
channels:
  - defaults
dependencies:
  - python=3.10
  - pandas=2.0.3
  - numpy=1.26.0
  - scikit-learn=1.3.0
  - xgboost=2.0.3
  - lightgbm=4.1.0
  - matplotlib=3.8.0
  - seaborn=0.12.2
  - notebook=7.0.4
  - jupyterlab=4.0.5
  - joblib=1.3.2